### PR TITLE
lots of big fixes, slight redesign.

### PR DESCRIPTION
**Pull request by ericbmerritt**

### CODE REVIEW

**Comment by tsloughter** [comment]
^ can't merge, Travis failed.

**Comment by jwilberding** [comment]
@ericbmerritt Travis still appears to be failing, did you look at that yet?

**Comment by ericbmerritt** [comment]
Not yet. Have not had time

Sent from my iPhone

On Jun 16, 2013, at 6:20, Jordan Wilberding notifications@github.com
wrote:

@ericbmerritt https://github.com/ericbmerritt Travis still appears to be
failing, did you look at that yet?

—
Reply to this email directly or view it on
GitHubhttps://github.com/erlware/erlnixify/pull/5#issuecomment-19512212
.

**Comment by jwilberding** [comment]
Eric, please fix.

**Comment by ericbmerritt** [comment]
I am not terribly sure how to fix it. Its a bad interaction of the checker
(which sucks a bit) and the opt parser which sucks a bit too. There isn't
awy to do it better with the opt parser, and there isn't a way to tell the
checker to ignore whats there.

**Comment by jwilberding** [comment]
Soo... merge anyways?

**Comment by ericbmerritt** [comment]
well, if we merge. I think we should turn off the checker or its always
going to break.

**Comment by jwilberding** [comment]
Want to just disable it now and update the PR?

**Comment by ericbmerritt** [comment]
I will probably do it in the morning man. I can't think right now :( sorry
man

**Comment by jwilberding** [comment]
No worries, hope all is well

**Pull request closed without merging**
